### PR TITLE
Add content to three main files and add resources

### PR DESCRIPTION
**Pull request by jrosen48**
This PR adds content to the three main files (`1_description.Rmd`, `2_faculty-format.Rmd`, and `3_narrative.Rmd`). It also adds resources to the `appendix` directory (which is now separated into sub-directories for `our-work` and `others-work`. Minor, but it also adds a few notes/possible content to include in a `notes.md` document in the (new) `planning` directory.

### CODE REVIEW

**Comment by datalorax** [comment]
This all looks great to me. If you want, feel free to just push to Master. But if there's stuff you want me to look at before pushing that's cool too.

**Comment by jrosen48** [comment]
Thank you! Okay, so, I was having trouble pushing directly... although I can definitely see that I am in the organization. Do you have any suggestions for how I can do it?

**Comment by datalorax** [comment]
Hmm... let me see if there's something messed up on the permissions.

**Comment by datalorax** [comment]
Okay, just changed your role to "Owner" (along with me) so you should be able to push to Master now. Do you want to try with some small commit just to make sure?

**Comment by jrosen48** [comment]
Good idea - just did in [this commit](https://github.com/ResearchTransparency/rr_aera19/commit/2bce34d764a5db566a763027617364f263b467f2); looks like it is all good to go.

**Pull request merged**
